#!/usr/bin/env python3
"""Generate the AOSS refresh-removal OVERLAY from the base spec.

Amazon OpenSearch Serverless rejects every explicit refresh value (true and
wait_for both 400; only the default false works, empirically verified). The
write-op `refresh` query parameter is therefore removed from the AOSS spec.

This must be done as an OVERLAY (project rule: overlay-only, no post-processing
scripts that mutate the built spec). But two openapi-overlays-js limitations
shape the overlay:
  * `update` MERGES/CONCATENATES arrays -- it cannot replace an array in place.
  * its JSONPath engine FORBIDS `$ref` filter predicates ("unsafe expression"),
    so array elements cannot be matched by their $ref value.
So for each operation carrying a refresh $ref we emit two actions: REMOVE the
whole `parameters` array, then re-add it filtered (remove-then-re-add = clean
replace). Plus: remove the 14 refresh component param defs and the now-orphaned
shared `_common___Refresh` schema.

This generator is authoring-time tooling. It writes overlays/aoss-refresh-remove
.overlay.yaml, which is what the build applies. Regenerate only if the base spec
or the upstream overlays change the refresh surface.

Usage: gen-refresh-remove-overlay.py <aoss-pre-spec.yaml> <out-overlay.yaml>
       (aoss-pre-spec = base after amazon-serverless + snapshot overlays)
"""
import os
import sys
import yaml


def is_refresh(p):
    return isinstance(p, dict) and str(p.get("$ref", "")).endswith("query.refresh")


def main() -> None:
    src, out = sys.argv[1], sys.argv[2]
    d = yaml.safe_load(open(src))
    params = d["components"]["parameters"]
    refresh_keys = [
        k for k, v in params.items()
        if isinstance(v, dict) and v.get("name") == "refresh" and v.get("in") == "query"
    ]

    actions = []
    op_count = 0
    for path, methods in d["paths"].items():
        if not isinstance(methods, dict):
            continue
        for m, op in methods.items():
            if not isinstance(op, dict) or "parameters" not in op:
                continue
            if not any(is_refresh(p) for p in op["parameters"]):
                continue
            filtered = [p for p in op["parameters"] if not is_refresh(p)]
            base = f"$.paths['{path}']['{m}']"
            actions.append({"target": f"{base}.parameters", "remove": True})
            actions.append({"target": base, "update": {"parameters": filtered}})
            op_count += 1

    for k in refresh_keys:
        actions.append({"target": f"$.components.parameters['{k}']", "remove": True})

    actions.append({"target": "$.components.schemas['_common___Refresh']", "remove": True})

    overlay = {
        "overlay": "1.0.0",
        "info": {"title": "AOSS refresh parameter removal", "version": "1.0.0"},
        "extends": "./opensearch-openapi.yaml",
        "actions": actions,
    }

    header = (
        "# GENERATED by tools/gen-refresh-remove-overlay.py -- do not hand-edit.\n"
        "# Removes the write-op `refresh` query parameter from the AOSS spec: AOSS\n"
        "# rejects every explicit refresh value (true/wait_for -> 400; only default\n"
        "# false works, verified against a real collection 2026-09-02).\n"
        "# Per operation: REMOVE the parameters array then re-add it filtered, because\n"
        "# openapi-overlays-js concatenates arrays on `update` and forbids $ref filter\n"
        "# predicates. Also removes the 14 refresh param defs + the orphaned\n"
        "# _common___Refresh schema.\n"
        f"# Covers {op_count} operations + {len(refresh_keys)} param defs + 1 schema.\n"
    )
    with open(out, "w") as f:
        f.write(header)
        yaml.safe_dump(overlay, f, sort_keys=False, width=4096)

    print(f"operations covered: {op_count}")
    print(f"param defs: {len(refresh_keys)}")
    print(f"total actions: {len(actions)}")
    print(f"written: {out} ({os.path.getsize(out)} bytes)")


if __name__ == "__main__":
    main()
